#!/bin/sh

. /etc/efingerd/log  # do some logging

printf "\nwelcome to\n"
figlet -f smslant envs.net
printf "is a minimalist, non-commercial\nshared unix system and will always be free to use.\n\n"
printf "we are linux lovers, programmer and users who like build webpages,\n"
printf "write blogs, chat online, play cool console games and so much more.\n"
printf "visit us on the web or gopher for more info\n"

if [ "$1" = "(null)" ]; then
  printf "hello %s,\n" "$2"
else
  printf "hello %s@%s\n" "$1" "$2"
fi

printf "users currently logged in are:\n\n"
who -uw | sort -u -k 1,1
printf "\n"
