#!/bin/sh

. /etc/efingerd/log

printf "\nwelcome to\n"
figlet -f smslant envs.net

cat <<EOM
envs.net is a minimalist, non-commercial
shared linux system and will always be free to use.

we are linux lovers, programmer and users who like build webpages,
write blogs, chat online, play cool console games and so much more.

you wish to join with an small user space?

https://envs.net/signup/
https://envs.net/
EOM

if [ "$1" = "(null)" ]; then
  printf "\n\nhello %s,\n" "$2"
else
  printf "\n\nhello %s@%s\n" "$1" "$2"
fi

printf "users currently logged in are:\n\n%s\n" "$(who -uw | sort -u -k 1,1)"
