#!/bin/sh

. /etc/efingerd/log

if [ "$1" = "(null)" ]; then
  printf "\nhello %s,\n\n" "$2"
else
  printf "\nhello %s@%s\n\n" "$1" "$2"
fi


if [ "$3" = "root" ]; then
  printf "you've reached\n"
  figlet -f smslant envs.net

  cat <<EOM
envs.net is a minimalist, non-commercial
shared linux system and will always be free to use.

we are linux lovers, programmer and users who like build webpages,
write blogs, chat online, play cool console games and so much more.

you wish to join with an small user space?

https://envs.net/
https://envs.net/signup/
EOM


elif [ "$3" = "gopher" ]; then
  printf "try port 70 :)\n\n"
  printf "gopher://envs.net\n"


else
  user_folder="/home/${3}"
  #/usr/bin/finger -m "$3"

  # Plan
  if [ -f "${user_folder}/.plan" ]; then
    printf "Plan:\\n"
    sed 's/^/  /' "${user_folder}/.plan"
  else
    printf "No Plan.\n"
  fi

  # Pronouns
  if [ -f "${user_folder}/.pronouns" ]; then
    printf "Pronouns:\\n"
    sed 's/^/  /' "${user_folder}/.pronouns"
  fi

  # Projects
  if [ -f "${user_folder}/.project" ]; then
    printf "Projects:\\n"
    sed 's/^/  /' "${user_folder}/.project"
  fi

  # Timezone
  if [ -f "${user_folder}/.tz" ]; then
    printf "Timezone: "
    cat "${user_folder}/.tz"
    printf "\n"
  fi

  # Online status
  if finger "$3" | grep -q 'On since'; then
    printf "Online.\n"
  else
    printf "Offline\n"
  fi

  # pgpkey
  if [ -f "${user_folder}/.pgpkey" ]; then
    printf "pgpkey:\\n"
    sed 's/^/  /' "${user_folder}/.pgpkey"
  fi

fi

exit 0
