#!/bin/sh

#. /etc/efingerd/log

echo
if [ "$1" = "(null)" ]; then
  echo hello "$2",
else
  echo hello "$1@$2",
fi

if [ "$3" = "time" ]; then
  echo The time is...
  date
  exit 0
fi

if [ "$3" = "envs" ]; then
  echo envs 4 a live
  exit 0
fi

if [ "$3" = "tilde" ]; then
  echo a tilde 4 u a tilde 4 me
  exit 0
fi

if [ "$3" = "ping" ]; then
  echo "PONG!"
  ping -c 5 "$2"
  exit 0
fi

if [ "$3" = "fortune" ]; then
  /usr/games/fortune
  exit 0
fi

if [ "$3" = "uptime" ]; then
  /usr/bin/uptime
  exit 0
fi

if [ "$3" = "uname" ]; then
  /bin/uname --all
  exit 0
fi

if [ "$3" = "new" ]; then
  echo visit https://envs.net/signup/ to request an account
  exit 0
fi

if [ "$3" = "signup" ]; then
  echo https://envs.net/signup/
  exit 0
fi

if [ "$3" = "gopher" ]; then
  echo try port 70
  exit 0
fi

echo "you've reached"
figlet -f smslant envs.net

cat <<EOM
envs.net is a minimalist, non-commercial
shared unix system and will always be free to use.

we are linux lovers, sysadmins, programmer and users who like build
webpages, write blogs, chat online, play cool console games and so much
more. you wish to join with an small user space?

join the team today!
https://envs.net/signup/
https://envs.net/

EOM
