#!/bin/sh

#. /etc/efingerd/log

if [ "$1" = "(null)" ]; then
  printf "hello %s,\n" "$2"
else
  printf "hello %s@%s\n" "$1" "$2"
fi


if [ "$3" = "time" ]; then
  printf 'The time is...\n'
  date
  exit 0
fi

if [ "$3" = "envs" ]; then
  printf "envs 4 a live\n"
  exit 0
fi

if [ "$3" = "tilde" ]; then
  printf "a tilde 4 u a tilde 4 me\n"
  exit 0
fi

if [ "$3" = "ping" ]; then
  printf "PONG!\n"
  ping -c 5 "$2"
  exit 0
fi

if [ "$3" = "fortune" ]; then
  /usr/games/fortune
  exit 0
fi

if [ "$3" = "uptime" ]; then
  /usr/bin/uptime
  exit 0
fi

if [ "$3" = "uname" ]; then
  /bin/uname --all
  exit 0
fi

if [ "$3" = "new" ]; then
  printf "visit https://envs.net/signup/ to request an account\n"
  exit 0
fi

if [ "$3" = "signup" ]; then
  printf "https://envs.net/signup/\n"
  exit 0
fi

if [ "$3" = "gopher" ]; then
  printf "try port 70\n"
  exit 0
fi

printf "you've reached\n"
figlet -f smslant envs.net

cat <<EOM
envs.net is a minimalist, non-commercial
shared linux system and will always be free to use.

we are linux lovers, programmer and users who like build webpages,
write blogs, chat online, play cool console games and so much more.

you wish to join with an small user space?

https://envs.net/signup/
https://envs.net/
EOM
